### ISSUE TITLE
Today view doesn't render

### ISSUE THREAD

**Issue by Powersource** [ActivityWatch/aw-webui#38]
The only complaint I get in the console is that `GET http://localhost:5600/bootstrap.css.map` 404s.

Doesn't work in Firefox nor incognito Chrome.

Everything is recently recursively cloned and running on node 7.10.1.

![image](https://user-images.githubusercontent.com/1427063/29129498-48586134-7d27-11e7-91a9-7782a00aa288.png)

**Comment by ErikBjare** [comment]
Alright, pretty sure I found the issue. Should be fixed in: https://github.com/ActivityWatch/aw-webui/commit/9a6f0bd5ffda4a39ffb0e815c81088edd3534af1

**Comment by ErikBjare** [comment]
I'm going to close this for now. Let me know if there is any further issue.

**Comment by ErikBjare** [comment]
If the error was what I thought it was, you should have gotten an error message however...

**Comment by johan-bjareholt** [comment]
Pulled latest master, doesn't render for me either. console.log says 

    TypeError: _.reverse is not a function

Will look further into this

**Comment by johan-bjareholt** [comment]
Seems to be at src/views/Today.vue:86

**Comment by ErikBjare** [comment]
@johan-bjareholt That's weird, worked fine for me and is clearly in lodash.

**Comment by ErikBjare** [comment]
@johan-bjareholt jQuery is not required for lodash. The only reason we have jQuery as a dependency is due to bootstrap afaik.

**Comment by ErikBjare** [comment]
This should have been fixed in https://github.com/ActivityWatch/aw-webui/pull/39/commits/7143721f7bf63d74663addbab75fcd916711e322, closing.

**Comment by Powersource** [comment]
I might be blind, but where is the Today view button?

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/29588077-6fc82a1a-8790-11e7-9068-cb88afc6dff9.png)

**Comment by ErikBjare** [comment]
Looks like you are running an old version.

**Comment by Powersource** [comment]
Ok I fucked up something there. But when I pull the latest aw-webui (manually, the main repo doesn't have it updated) I get in but it still doesn't render.

![image](https://user-images.githubusercontent.com/1427063/29611992-0905eae0-8800-11e7-8dab-b00d6caf46fc.png)

And just for the record, when I run `make build`, it updates the package-lock.json in aw-webui (git status mentions it changing). Should it do that?

**Comment by ErikBjare** [comment]
Don't worry about the package-lock.json, I haven't fully gotten into how npm handles it but it does seem to change on a lot of npm commands...

I've updated the main repo, try pulling it and see if that helps. You might also want to remove your node_modules.

**Comment by johan-bjareholt** [comment]
Works fine for me now!

**Comment by Powersource** [comment]
Worked once I re-cloned everything.

And I think that since `make build` scraps the lock that is already there, it feels like we could skip having it in git.

**Comment by ErikBjare** [comment]
It shouldn't scrap the `package-lock.json`, it should just update it if necessary. That's my understanding as least.
